name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install library
      run: poetry install
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Node.js dependencies
      run: npm ci
    
    - name: Analysing the code with pylint
      run: |
        poetry run pylint --fail-under=9.9 $(git ls-files '*.py')
    - name: Synthesize CDK stack
      run: |
        node --loader ts-node/esm bin/pipeline-cdk.ts
    - name: Run unit tests
      run: |
        poetry run python -m pytest tests
