name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install library
      run: uv sync --dev
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Node.js dependencies
      run: npm install
    
    - name: Analysing the code with pylint
      run: |
        uv run pylint --fail-under=9.9 $(git ls-files '*.py')
    - name: Synthesize CDK stack
      env:
        CDK_DOCKER: "false"
      run: |
        npm install -g aws-cdk@^2.1018.1
        npx cdk synth --no-staging
    - name: Run unit tests
      run: |
        uv run python -m pytest tests
